apiVersion: apps/v1
kind: Deployment
metadata:
  name: csicvmfs-demo-depl
  labels:
    app: csicvmfs-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csicvmfs-demo
  template:
    metadata:
      labels:
        app: csicvmfs-demo
    spec:
      containers:
       - name: demo
         image: busybox
         imagePullPolicy: IfNotPresent
         command: [ "/bin/sh", "-c", "trap : TERM INT; (while true; do sleep 1000; done) & wait" ]
         volumeMounts:
           - name: mypvc
             mountPath: /cms.cern.ch
      volumes:
       - name: mypvc
         persistentVolumeClaim:
           claimName: csi-cvmfs-pvc
           readOnly: false
