# Create StorageClass for provisioning CVMFS automount volumes,
# and a PersistentVolumeClaim that's fulfilled by the StorageClass.

# If Controller plugin is not deployed, follow the example in volume-pv-pvc.yaml.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cvmfs
provisioner: cvmfs.csi.cern.ch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      # Volume size value has no effect and is ignored
      # by the driver, but must be non-zero.
      storage: 1
  storageClassName: cvmfs
