{{- if .Values.controllerplugin.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cvmfs-csi.serviceAccountName.controllerplugin" . }}
  labels:
    {{- include "cvmfs-csi.controllerplugin.labels" .  | nindent 4 }}
{{- end }}

