apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.csiDriverName }}
  labels:
    {{- include "cvmfs-csi.common.metaLabels" .  | nindent 4 }}
spec:
  attachRequired: false
  podInfoOnMount: false
