{{- if .Values.nodeplugin.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cvmfs-csi.serviceAccountName.nodeplugin" . }}
  labels:
    {{- include "cvmfs-csi.common.metaLabels" .  | nindent 4 }}
{{- end }}
