{{- $baseName := include "cvmfs-csi.fullname" . }}
{{ if .Values.prefetcher.enabled }}
{{- range .Values.prefetcher.jobs }}
{{- $entrypointConfigMap :=  printf "%s-%s" $baseName .name | trunc 63 | trimSuffix "-" }}
---
apiVersion: v1
kind: CronJob
metadata:
  name: {{ printf "%s-%s" $baseName .name | trunc 63 | trimSuffix "-" }}
  labels: 
    {{- include "cvmfs-csi.common.labels" $ | nindent 4 }}
    job: {{ .name }}
spec:
  schedule: {{ quote .schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          securityContext: {{ toYaml $.Values.prefetcher.securityContext | nindent 12 }}
          containers:
            - name: prefetcher
              image: {{ $.Values.prefetcher.image.repository }}:{{ $.Values.prefetcher.image.tag | default $.Chart.AppVersion }}
              imagePullPolicy: {{ $.Values.prefetcher.image.pullPolicy }}
              command:
                - "/bin/sh"
                - "-c"
                - "/etc/cvmfs-csi/prefetcher/{{ .name }}/entrypoint.sh"
              volumeMounts:
                - name: prefetcher-script
                  configMap:
                    name: {{ $entrypointConfigMap }}
                - name: autofs-root
                  mountPath: /cvmfs
                  mountPropagation: Bidirectional
              securityContext:
                capabilities:
                  drop: 
                    - ALL
      backoffLimit: 3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $entrypointConfigMap }}
  labels: 
    {{- include "cvmfs-csi.common.labels" $ | nindent 4 }}
    job: {{ .name }}
spec:
  entrypoint.sh: {{ toYaml .script | indent 2 }}
{{- end }}
{{- end }}
