{{- $baseName := include "cvmfs-csi.fullname" . }}
{{ if .Values.prefetcher.enabled }}
{{- range .Values.prefetcher.jobs }}
{{- $entrypointConfigMap :=  printf "%s-prefetcher-%s" $baseName .name | trunc 63 | trimSuffix "-" }}
{{- $defaultPrefetchImage := printf "%s:%s" $.Values.prefetcher.image.repository ($.Values.prefetcher.image.tag | default $.Chart.AppVersion) -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-prefetcher-%s" $baseName .name | trunc 63 | trimSuffix "-" }}
  labels: 
    {{- include "cvmfs-csi.common.labels" $ | nindent 4 }}
    job: {{ .name }}
spec:
  schedule: {{ quote .schedule }}
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: "OnFailure"
          securityContext: {{ toYaml $.Values.prefetcher.podSecurityContext | nindent 12 }}
          containers:
            - name: prefetcher
              image: {{ .image | default $defaultPrefetchImage }}
              imagePullPolicy: {{ $.Values.prefetcher.image.pullPolicy }}
              command:
                - "/bin/sh"
                - "-c"
                - "/etc/cvmfs-csi/prefetcher/{{ .name }}/entrypoint.sh"
              volumeMounts:
                - name: autofs-root
                  mountPath: /cvmfs
                  mountPropagation: Bidirectional
                - name: prefetcher-script
                  mountPath: "/etc/cvmfs-csi/prefetcher/{{ .name }}"
              securityContext:
                privileged: true
                capabilities:
                  drop: 
                    - ALL
          volumes:
            - name: autofs-root
              hostPath:
                path: {{ $.Values.automountHostPath }}
                type: DirectoryOrCreate
            - name: prefetcher-script
              configMap:
                name: {{ $entrypointConfigMap }}
                defaultMode: 0777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $entrypointConfigMap }}
  labels: 
    {{- include "cvmfs-csi.common.labels" $ | nindent 4 }}
    job: {{ .name }}
data:
  entrypoint.sh: {{ toYaml .script | indent 2 }}
{{- end }}
{{- end }}
