{{- range $key, $rep := .Values.repositories -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $key }}
  labels:
    app.kubernetes.io/name: {{ include "cvmfs-csi.name" $ }}
    helm.sh/chart: {{ include "cvmfs-csi.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app: csi-cvmfsplugin
provisioner: {{ $.Values.provisioner }}
parameters:
  repository: {{ $rep }}

---
{{ end }}
