apiVersion: v1
kind: ServiceAccount
metadata:
  name: cvmfs-nodeplugin
  namespace: cvmfs

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cvmfs-nodeplugin
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "update"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cvmfs-nodeplugin
subjects:
  - kind: ServiceAccount
    name: cvmfs-nodeplugin
    namespace: cvmfs
roleRef:
  kind: ClusterRole
  name: cvmfs-nodeplugin
  apiGroup: rbac.authorization.k8s.io

  